### ISSUE TITLE
(psycopg.OperationalError) connection failed: Connection refused web-1  |Is the server running on that host and accepting TCP/IP connections?

### ISSUE THREAD

**Issue by sasha-vtz** [mgurg/fastapi_docker#23]
When i check db health i rececive the error
(psycopg.OperationalError) connection failed: Connection refused web-1  |Is the server running on that host and accepting TCP/IP connections?

Funny, when i run the FastAPI app  in virtual enviroment and connect to database in Docker it works!

It seems that problem is with connection FastAPI and Postgresql when they both are in the container

**Comment by mgurg** [comment]
I'm rewriting whole app in [here](https://github.com/mgurg/fastapi_docker/tree/feature/db_repository_pattern) I will check it somewhere in the future in new codebase
